// Computes the two provenance commitments written into ledger state at deploy:
//   policyHash        sha256 of POLICY.md, the eligibility policy this cohort opened under
//   circuitCommitment sha256 of the verifier key, identifying the exact circuit
// Both are constant size, set once, and carry no per-contributor information.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const sha256 = (path) =>
  createHash('sha256').update(readFileSync(path)).digest('hex');

const VERIFIER = 'managed/cohort/keys/contribute.verifier';
if (!existsSync(VERIFIER)) {
  console.error(`${VERIFIER} missing. Run: npm run compact`);
  process.exit(1);
}

const policyHash = sha256('POLICY.md');
const circuitCommitment = sha256(VERIFIER);

// Emitted as an ES module rather than JSON so it loads identically under Node
// and Vite without needing import attributes.
const source = [
  '// GENERATED by scripts/provenance.js. Do not edit by hand.',
  '// policyHash        = sha256(POLICY.md)',
  '// circuitCommitment = sha256(managed/cohort/keys/contribute.verifier)',
  'export const PROVENANCE = {',
  `  policyHash: '${policyHash}',`,
  `  circuitCommitment: '${circuitCommitment}',`,
  '};',
  '',
].join('\n');

writeFileSync('src/provenance.js', source);
console.log('policyHash        ', policyHash);
console.log('circuitCommitment ', circuitCommitment);
