// GENERATED by scripts/provenance.js. Do not edit by hand.
// policyHash        = sha256(POLICY.md)
// circuitCommitment = sha256(managed/informer/keys/contribute.verifier)
export const PROVENANCE = {
  policyHash: '2824e28f901b355198c2271e9ba5b9e82ec00133425bae2fd6344d43b3e5e611',
  circuitCommitment: '29dd77e52c827b3cd48384ea26fa55be4838d56e6263faa3d8b5d838e75ff25f',
};
