// GENERATED by scripts/provenance.js. Do not edit by hand.
// policyHash        = sha256(POLICY.md)
// circuitCommitment = sha256(managed/cohort/keys/contribute.verifier)
export const PROVENANCE = {
  policyHash: 'e5d22da8870be980043d13d1ed86f0c2d57c86a6b062fafcbe64ec228a7cb62a',
  circuitCommitment: '29dd77e52c827b3cd48384ea26fa55be4838d56e6263faa3d8b5d838e75ff25f',
};
